### ISSUE TITLE
Has the location of keys and certs changed?

### ISSUE THREAD

**Issue by rsignell-usgs** [BradJonesLLC/docker-nginx-letsencrypt#4]
I'm getting docker log errors like:
```
[emerg] 24#24: BIO_new_file("/etc/ssl/le-first/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/ssl/le-first/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
```
and indeed, when I login to the container, these files are not in `/etc/ssl/le-first`.

I did find `fullchain.pem` (and the 3 other .pem files) in `/etc/letsencrypt/live/js-170-55.jetstream-cloud.org`. 

My `docker-compose.yml` looks like this:
```
nginx:
  image: bradjonesllc/docker-nginx-letsencrypt
  ports:
    - "80:80"
    - "443:443"
  container_name: nginx
  volumes:
    - /opt/docker/brad/dhparam:/etc/ssl/dhparam
    - /opt/docker/brad/letsencrypt:/etc/letsencrypt
    - /opt/docker/nginx/html:/etc/nginx/html
    - /opt/docker/nginx/conf.d/brad.conf:/etc/nginx/conf.d/brad.conf
    - /opt/docker/nginx/conf.d/include/cors.include:/etc/nginx/conf.d/include/co
rs.include
  environment:
    - "CERTS=js-170-55.jetstream-cloud.org"
    - "EMAIL=rsignell@usgs.gov"
```
Do I need to change the volume mounts?
